# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-27 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0003_auto_20210116_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='exibir_menu',
            field=models.BooleanField(default=False),
        ),
    ]
