# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-14 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('decricao', models.TextField()),
                ('foto', filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Image')),
            ],
        ),
    ]
