# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-27 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_auto_20210114_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='exibir_categoria',
            field=models.BooleanField(default=False),
        ),
    ]
