# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-27 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_auto_20210127_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='exibir_menu',
            new_name='exibir_categoria',
        ),
    ]
