# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-27 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0006_auto_20210127_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='exibir_categoria',
            field=models.BooleanField(default=False),
        ),
    ]
